  name: Spring Boot Github Action

  on:
    push :
      branches:
        - main
  jobs:
    test:
      runs-on: ubuntu-latest
      name: Test
      steps:
        - run: echo "running test"
        - uses: actions/checkout@v3
        - name: Setup JDK 11
          uses: action/setup-java@v3
          with:
            java-version: 11
            distribution: 'adopt'
        - name: Maven Verify
          run: mvn clean verify

    build:
      name: Build
      runs-on: ubuntu-18.04
      needs: run_test
      steps:
        - run: echo "Building package"
        - uses: actions/checkout@v3
        - name: Setup JDK 11
          uses: actions/setup-java@v3
          with:
            java-version: 11
            distribution: 'adopt'
        - name: Maven Build
          run: mvn clean package -Dmaven.test.skip=true
        - name: Login to docker hub
          uses: docker/login-action@v1
          with:
            username: ${{ DOCKERHUB_USERNAME }}
            password: ${{ DOCKERHUB_TOKEN }}
        - name: Build docker image
          uses: docker/build-push-action@v2
          with:
            context: .
            push: true
            tags: rofiksupriant/spring-helloworld:latest
    deployment:
      name: Deploy to Server
      runs-on: ubuntu-latest
      needs: build
      steps:
        - run: echo "Deploying to Server"
        - uses: actions/checkout@v3
        - name: Deploy using ssh
          uses: appleboy/ssh-action@master
          with:
            host: ${{ EC2_SSH_HOST }}
            port: 22
            username: ${{ EC2_SSH_USERNAME }}
            key: ${{ EC2_SSH_PRIVATE_KEY }}
            script: |
              docker stop spring-helloworld
              docker rmi  rofiksupriant/spring-helloworld:latest
              docker pull  rofiksupriant/spring-helloworld:latest
              docker run -d --rm --name spring-helloworld -p 80:8080 -p 443:8080 --network kampus_merdeka rofiksupriant/spring-helloworld:latest